#
# kubectl apply -k .
#
# The Images are  about 200M [2].  The php-fpm image  does not seem to
# bring a proxy and  does not speak http on its  port 9000. The Apache
# image ist called "legacy" OTOH. It does serve content though.
#
# When going through the installation specify "root" as the MySQL root
# password and "idoit-db" as the  hostname for the MySQL server. Cross
# check below if this comment gets out of date.
#
# Note that there  appears to be no simple way  to "reconnect" a fresh
# pod with unmodified /var/www/html to an existing DB -- the installer
# insists on dropping the DB.
#
# If  you ever  going  to kill  the  Pod  and expect  the  new one  to
# reconnect to the  existing DB you seem  to need to bring  all of (?)
# the old  /var/www/html with the src/config.in.php  and whatever else
# is required. Because of this alone you may want need to persist this
# data to a volume:
#
#     Each  i-doit container  has  one default  volume containing  the
#     complete installation directory:  /var/www/html.  This directory
#     includes the source code, cache files, uploaded files, installed
#     add-ons, custom translation files, etc.
#
# Just dont  expect to be able  to keep that data  upon update.  There
# seem  to be  a  generated src/config.in.php,  what  else is  equally
# critical?
#
# [1] https://github.com/bheisig/i-doit-docker
# [2] https://hub.docker.com/r/bheisig/idoit
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idoit-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: idoit-server
  template:
    metadata:
      labels:
        component: idoit-server
    spec:
      # Volumes used by some or all containers of the Pod:
      volumes:
      - name: "idoit-data"
        persistentVolumeClaim:
          claimName: "idoit-data"
      containers:
      - name: idoit-server
        # docker run --name i-doit-apache -p 80:80 bheisig/idoit:1.15-open-php7.4-apache
        image: bheisig/idoit:1.15-open-php7.4-apache
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        # The  simplest   way  to   persist  data   between  container
        # starts/upgrades is to utilize  named volumes.  You would not
        # want to keep the old sources on upgrade though.  This volume
        # *does* contain  the PHP sources,  though.  Thus you  may not
        # expect updates to work.  You have to start from scratch with
        # every version change of an  image.  Delete the volume or the
        # whole namespace and re-create ...
        volumeMounts:
        - mountPath: "/var/www/html"
          name: "idoit-data"
        env:
        - name: "XXX"
          value: "yyy"
      initContainers:
      - name: idoit-init
        # FIXME: should be the same as above:
        image: bheisig/idoit:1.15-open-php7.4-apache
        # When  exactly does  a  volume  need (re)initialization?   We
        # simply look if src/ directory exists:
        command: ["sh", "-c", "test -d /d/src || tar cf - -C /var/www/html . | tar xf - -C /d"]
        # command: ["tail", "-f", "/dev/null"]
        volumeMounts:
          - mountPath: "/d"
            name: "idoit-data"
---
apiVersion: v1
kind: Service
metadata:
  name: idoit-server
spec:
  type: ClusterIP
  selector:
    component: idoit-server
  ports:
  - port: 80
    targetPort: 80
---
#
# We  assume here  that  *.localhost resolves  to  the local  machine.
# Following URL should be directed to corresponding Service, also with
# https:// protocoll:
#
#     http://idoit.localhost
#
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: idoit
spec:
  rules:
  - host: idoit.localhost
    http:
      paths:
      - backend:
          serviceName: idoit-server
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idoit-db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: idoit-db
  # Strategy  =  Recreate  instructs  Kubernetes to  not  use  rolling
  # updates.  Rolling updates  will not work, as you  cannot have more
  # than one  Pod running at a  time. The Recreate strategy  will stop
  # the  first  pod  before  creating  a  new  one  with  the  updated
  # configuration.
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: idoit-db
    spec:
      # Volumes used by some or all containers of the Pod:
      volumes:
      - name: "idoit-db"
        persistentVolumeClaim:
          claimName: "idoit-db"
      containers:
        # docker run --name some-mysql -e
        # MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:tag
        #
        # MySQL v8.0 is not supported as of v1.15.  Use 5.7 ...
      - name: idoit-db
        image: mysql:5.7.32
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: "idoit-db"
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "root"
          # Let the Idoit Startup Procedure create the DB, avoid
          # collation issues:
        # - name: "MYSQL_USER"
        #   value: "idoit"
        # - name: "MYSQL_PASSWORD"
        #   value: "idoit"
        # - name: "MYSQL_DATABASE"
        #   value: "idoit"
---
apiVersion: v1
kind: Service
metadata:
  name: idoit-db
spec:
  type: ClusterIP
  selector:
    component: idoit-db
  ports:
  - port: 3306
    targetPort: 3306
---
# https://github.com/rancher/local-path-provisioner
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: idoit-data
spec:
  accessModes:
    - ReadWriteOnce
  # When you  dont specify  storage class at  all the  default storage
  # class may be chosen. In k3s with local-path provisioner it is also
  # the  default one.  Omitted  storageClassName is  not  the same  as
  # storageClassName = "".
  # storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: idoit-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
...
